name: C CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ncurses
        run: sudo apt-get update && sudo apt-get install -y libncurses-dev
      - name: Build
        run: make
      - name: Run (quick test)
        run: timeout 2 ./snake_game || true   # chạy 2 giây rồi kill
